### PR TITLE
Make sure "footerperformance" is not null

### PR DESCRIPTION
**Pull request by nadavkav**
Was getting an error while opening a question preview window (layout popup) with no "footer .footerperformance" element.
So added a check for its availability.

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks Nadav,

I don't know how I missed that.  Just needs a little tidying up.

I wonder if there are any other cases in the footer that need the logic.

Cheers,

Gareth

**Comment by nadavkav** [comment]
Updated

**Comment by gjb2048** [comment]
Ok, still not sorted, but will pull and rectify myself.

**Comment by nadavkav** [comment]
J to save the day! Bless you :smile:

**Comment by nadavkav** [comment]
btw, this week I manage to "Convert" 2 major colleges (Sapir & Shenkar) and one major university (Haifa) to Essentialism!!! a second before going fully online. yes!

**Comment by gjb2048** [comment]
:)

Re-write: https://github.com/gjb2048/moodle-theme_essential/commit/17da0f5d557fc2391ed20ac755f3242ceb61ccc9.

**Pull request merged**
