### PR TITLE
Don't smooth scroll when href is for a different page

### LINKED ISSUE #659: Links with anchors don't work with the "flexsections" course format.
In v3.0.1.2, if you are using the flexsections course format (https://github.com/marinaglancy/moodle-format_flexsections) with collapsed sections, there is a bit of javascript that breaks the links that take you from a section page back to the course.  The section page (at `.../course/view.php?id=71&sectionid=1084`) has a link that looks like `.../course/view.php?id=71&section=0#section-2`, but clicking the link scrolls the page so that this link is at the top instead of taking you back to the course page.  I think this happens at https://github.com/gjb2048/moodle-theme_essential/blob/V3.0.1.2/amd/src/course_navigation.js#L30, but I can't make it stop by commenting it out, so I could be wrong.  

More generally, it's probably the case that any link to another page with an #anchor is going to be broken by that click handler.

### PR DESCRIPTION
**Pull request by jk3us**
This fixes #659.  Note that `$(this).href` will always get a full url (absolute, with host and all), while `$(this).attr('href')` will get the literal string in the href attribute. Using the former will treat relative urls correctly, while the latter won't.  This fix will cause the smooth scrolling code to only run if the urls only differ by the hash value. Somewhat based on http://stackoverflow.com/a/4198114/2262822, but that code doesn't consider get parameters in the URL, while this one does.

### CODE REVIEW

**Comment by gjb2048** [comment]
Hi Jay,

Whilst I appreciate the solution and indeed it is progress, I believe that it would be better and more efficient not to even bother adding the 'click' handler if '(url.substring(0,url.indexOf('#')) != location.href.substring(0,location.href.indexOf('#')))' is true.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Or even do add the handler if '(url.substring(0,url.indexOf('#')) == location.href.substring(0,location.href.indexOf('#')))' is true.

**Comment by gjb2048** [comment]
And clearly the result of 'location.href.substring(0,location.href.indexOf('#'))' can be put in a variable to reduce the repeated calls to 'substring' for every link in the iteration.

**Comment by gjb2048** [comment]
Therefore, please improve the code, combine into one commit and let me know when that is done.  Thank you :).

**Comment by gjb2048** [comment]
Also... the patch only has the 'src' - to be complete the 'build' version needs to be there too with 'grunt amd'.

**Comment by jk3us** [comment]
Updated.  I think this addresses all of your concerns above. Thanks.

**Comment by gjb2048** [comment]
Thanks Jay, I'll review as soon as I can.

**Comment by gjb2048** [comment]
Ok, in testing, does not cope with links on the same site but on a different page.

**Comment by gjb2048** [comment]
Therefore the code needs to be improved such that the default behaviour happens when same site and different page, but not when same site and same page.

**Comment by gjb2048** [comment]
Oh..... and the code further fails when there is no anchor for 'page_href_base' so with respect Jay, did you actually test this?

**Comment by gjb2048** [comment]
This is a confusing mess.

**Comment by gjb2048** [comment]
Also with "at .../course/view.php?id=71&sectionid=1084) has a link that looks like .../course/view.php?id=71&section=0#section-2" it is the same page but with an extra get parameter.

**Comment by jk3us** [comment]
>Therefore the code needs to be improved such that the default behaviour happens when same site and different page, but not when same site and same page.

For me, urls that go to the exact same url with an added or different hash, the smooth scrolling behavior remains, but for any links to different URLs (regardless of their hash) the browser's default behavior is allowed to handle it.

>the code further fails when there is no anchor for 'page_href_base' so with respect Jay, did you actually test this?

I've pushed a new commit that fixes this: https://github.com/jk3us/moodle-theme_essential/commit/e6483b08161228d4b8bb12f29928a2963caf88fc

>Also with "at .../course/view.php?id=71&sectionid=1084) has a link that looks like .../course/view.php?id=71&section=0#section-2" it is the same page but with an extra get parameter.

If the URL is different, you have to assume that it points to a different resource. So even though the two urls produce the exact same output, this code has no way of knowing that for sure and should let the browser handle the navigation.

**Comment by gjb2048** [comment]
But with the scenario of current page of 'view.php?id=71' and destination of 'view.php?id=72#section-2' then the JS has to do the scroll after the page navigation to the page for the very reason the code was created in the first place.

**Comment by gjb2048** [comment]
Thanks for the patch, but as you can see in: https://github.com/gjb2048/moodle-theme_essential/blob/master/amd/src/course_navigation.js#L30-L55 I've already handled this and taken it further to scroll when you arrive at the destination on the same site and need to take the navbar into account.

**Pull request merged**
