### PR TITLE
Add setting to display a page editing menu/button on the header

### PR DESCRIPTION
**Pull request by jojoob**
I've added a setting to display a page editing button on the header (right side).
editing button

This button has the same functionality as the default "Turn editing on/off" button on the top right of a page. The button on the header is only displayed if the setting is turned on and the user is allowed to edit the page.
editingmenu setting

In addition another setting allows to disable/remove the default button from any page.
editingmenu default disabled

### CODE REVIEW

**Comment by gjb2048** [comment]
Hi Johannes,

Nice, I like it :) - before I can merge, please rebase your branch so that only your commit https://github.com/sudile/moodle-theme_essential/commit/e05e84044b3906ffcb91d031d83821cc037f22d4 is in the pull otherwise it will make a mess of the branch.  If not I'll have to cherry pick it.

Cheers,

Gareth

**Comment by jojoob** [comment]
Oh, I see. I actual want to make the pull request against the MOODLE_29 branch...
Will you merge this into master or MOODLE_29?

**Comment by gjb2048** [comment]
rebase on master please and I'll pull on MOODLE_29 as both currently in-sync.

**Comment by jojoob** [comment]
done!

**Comment by gjb2048** [comment]
Thanks Johannes,

In looking at the patch I'm worried about https://github.com/sudile/moodle-theme_essential/commit/1dae2a17031c166c49dae4e53ca69d728a7003bd#diff-bb06945c9eaa3c6e1047bb59790e9755R653 - being a reference to the page URL object and not a clone of it as the object is being changed.  Ref: http://php.net/manual/en/language.oop5.cloning.php

Does the moodle_url have a 'clone' method?

What are your thoughts please.

Cheers,

Gareth

**Comment by jojoob** [comment]
moodle_url has no clone method but the constructor allows to instantiate a new moodle_url from an existing instance.

But we have not to worry about it in this case since the url member of moodle_page is protected and so the magic get method is called which clones the url for us: https://github.com/moodle/moodle/blob/master/lib/pagelib.php#L565.

**Comment by jojoob** [comment]
But if we want the code more clear (don't rely on magic get method) we could do `$url = new moodle_url($this->page->url);`

**Comment by gjb2048** [comment]
Thanks for the information, given the extra checks: https://github.com/moodle/moodle/blob/master/lib/pagelib.php#L559-L564 - then leave as is.

**Comment by gjb2048** [comment]
Thanks Johannes,

All merged in master and MOODLE_29 branches, I'd left things a bit odd so had to rebase master against MOODLE_29, therefore you may have to fetch and reset hard etc. or force checkout of remote to get the branch sorted.

Cheers,

Gareth

**Comment by gjb2048** [comment]
P.S.  Commit credit has been kept.

**Comment by jojoob** [comment]
Thank you for integrating this so fast!

**Comment by gjb2048** [comment]
Hi Johannes,

Please see: https://github.com/gjb2048/moodle-theme_essential/issues/595 - as the solution has been found to be incomplete.

What do you suggest?

Gareth

**Pull request merged**
