### PR TITLE
Accessibility: missing aria-label attribute in "prev"/"next" elements

### PR DESCRIPTION
**Pull request by nadavkav**
One more

### CODE REVIEW

**Comment by gjb2048** [comment]
How does this work with RTL?

**Comment by nadavkav** [comment]
If looked at the icons alone, someone without a screen reader will not care. as the arrows do not have labels. if they did, we should have "prev" pointing to the right in RTL mode.

Seems like all slides information is equally important and their order is not relevant (as we are not reading a book, going the ordered topics in a course or going linearly in some narrative) so RTL and LTR of arrows is not important too.

So I just translated the text in the base of the arrows. so the screen reader could say "previous" or "next" in the proper language.

**Comment by gjb2048** [comment]
Oh, I mean is 'left' still on the physical left and vice versa?

**Comment by nadavkav** [comment]
Thanks.

Left/Right & Previous/Next should be flipped most of the times. except when their is no linear meaning.
If you want to be super (super) pleasant... it should be flipped. in the php code. (as we do in Moodle core on many [cases](https://github.com/moodle/moodle/blob/master/lib/weblib.php#L3137) & [mostly](https://github.com/moodle/moodle/blob/master/lib/weblib.php#L3124) )

**Comment by gjb2048** [comment]
For this I did do in the past only discover that it was wrong.

**Pull request merged**
