### PR TITLE
added support for composer installers

### PR DESCRIPTION
**Pull request by forloops**
see: https://github.com/composer/installers for details. short summary: this composer file will let everyone install the theme using composer installers in the correct directory

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks for the patch and I'm intrigued.  As surely people will ask how to do this, please could you tell me / provide instructions on using it and screen shots of it working to install the theme in a Moodle installation.  As even though I'm keen, I will have to maintain and answer questions about it and I don't want to appear to be a Muppet.

**Comment by forloops** [comment]
Of course :) 

[Composer](https://getcomposer.org/) is a tool for dependency management in PHP. It allows you to declare the dependent libraries your project needs and it will install them in your project for you. [Once you install it](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx), you create a composer.json file in the root folder of your project. 

At the moment, the [github moodle repository](https://github.com/moodle/moodle/blob/master/composer.json) has one already created. What you would do is edit it.

existing composer.json example:

```
{
    "repositories" : [
        {
            "type": "vcs",
            "url": "https://github.com/moodlehq/moodle-behat-extension"
        }
    ],
    "require-dev": {
        "phpunit/phpunit": "3.7.*",
        "phpunit/dbUnit": "1.2.*",
        "moodlehq/behat-extension": "1.29.5"
    }
}
```

Updated:

```
{
    "repositories" : [
        { "type": "vcs", "url":  "https://github.com/moodlehq/moodle-behat-extension" }
    ],
    "require": {
    	"composer/installers":"~1.0",
    	"gjb2048/moodle-theme-essential":"dev-master",
    },
    "require-dev": {
        "phpunit/phpunit": "3.7.*",
        "phpunit/dbUnit": "1.2.*",
        "moodlehq/behat-extension": "1.25.6"
    }
}
```

Notice we added the "require" part. composer/installers is the first package. What composer will do is go out and check the [Packagist](https://packagist.org/) website to see if the package is listed. If it is not listed, it will go out and check github for it. The package ["composer/installers"](https://github.com/composer/installers) contains information on how to install specific packages for different platforms (ie: WordPress, Moodle, Drupal, Laravel, etc.). [You can specify what version, branch or tag to use](https://getcomposer.org/doc/01-basic-usage.md#package-versions).

The second item is the essential theme. In the example above, we are requesting "dev-master' which will pull everything from the master branch.

Once you have the composer.json file modified, you run the command ```composer install ``` via the command line and it will create a vendor folder, put any 3rd party code in there and any Moodle related composer packages will get installed in their respective directory. You can find out more about the install paths [HERE](https://github.com/composer/installers/blob/master/src/Composer/Installers/MoodleInstaller.php) and [HERE](https://github.com/composer/installers/blob/master/README.md)

The final part is to add the autoload.php file that Composer also prepares, that's capable of autoloading all of the classes in any of the libraries that it downloads. What I do is add the following in my config.php:

```
if( file_exists(__DIR__ . '/vendor/autoload.php') ) { 
    require __DIR__ . '/vendor/autoload.php'; 
}
```

When you want to update your packages, you can simply run ``` composer update``` from the command line and it will update all the packages and re-create a fresh autoload.php file.


I highly recommend reading up on the following:

- [Composer Official Documentation](https://getcomposer.org/)

- [Composer Installers](https://github.com/composer/installers)


I hope this helps... if not, please let me know and I will do my best to help clarify any issues.

Thanks!

**Comment by gjb2048** [comment]
Thank you for your lengthy reply Edward :) - a lot to take in!  Will take a while.

**Comment by gjb2048** [comment]
I've not forgotten about this!

**Comment by gjb2048** [comment]
Is this needed: https://github.com/bmbrands/theme_bootstrap/blob/master/composer.json#L4-L6 ?

**Comment by gjb2048** [comment]
Also looking at https://github.com/bmbrands/theme_bootstrap/blob/master/composer.json#L2, there is a coding fault in the patch using a hyphen instead of an underscore in the name: https://github.com/gjb2048/moodle-theme_essential/pull/508/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R2.

**Comment by forloops** [comment]
apologies - I was on vacation. https://github.com/bmbrands/theme_bootstrap/blob/master/composer.json#L4-L6

it is best practice to include it. I had mine defined in the main moodle composer.json because I forked the original composer/installers and use a private repository with extra install paths, and scripts. For some reason composer will not not pick up the private repos that are listed in the require section from sub components. Thus the work-around for including it in the main one.

Thanks

**Comment by gjb2048** [comment]
Thanks, please see #513.

**Pull request merged**
