### PR TITLE
New settings that might be useful to other users

### PR DESCRIPTION
**Pull request by mikhailjan**
I have created a child theme of Essential but I thought some of my changes might be useful to other users so I have added them to the Essential theme. Please have a look and let me know if you are happy to merge them or if you want me to make changes.

The settings I added are:
- Custom favicon
- Logo height
- Turn off CSS styling of scrollbars

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks for the patch Mikhail, I will look at it as soon as I can, so many things to do!  But before that, please could you combine all of the commits into one so that backporting is easy for me and there is no confusion over the merges.

**Comment by mikhailjan** [comment]
Hi Gareth, I have rebased my commits into one.

**Comment by gjb2048** [comment]
Thanks Mikhail, I will look when I get time.

**Comment by gjb2048** [comment]
Notes:

favicon method needs to use theme method of getting images.

Nothing in Gruntfile.js for building the scrollbar less.

**Comment by gjb2048** [comment]
Branch https://github.com/gjb2048/moodle-theme_essential/tree/MOODLE_29_%23574 created with cherry picked commit to tidy things up in.

**Comment by gjb2048** [comment]
As unable to pull due to conflicts, have cherry picked to maintain original author details.

**Comment by gjb2048** [comment]
Fixes made in: https://github.com/gjb2048/moodle-theme_essential/commit/f4697f6e51bbfe2596d7e022b8777d4048034a1d

**Comment by dschwa** [comment]
Gareth,

Any idea when Essential 3.0 will be available?  It works, but throws
version errors, plus there are minor issues. Mostly the custom css is not
working.

Love the theme and have a request into my client for a donation to help
continued development.

Don Schwartz

**Comment by mikhailjan** [comment]
Hi Gareth,

It's nice to see that there is a better way to get the favicon file url and thank you for updating Gruntfile.js. Please let me know if there is anything I still need to do.

**Comment by mikhailjan** [comment]
I needed to display a logo together with some text in the header, and currently the header title is not displayed if you upload a logo. So I have made changes to allow this. It required me to add a logo width setting to work properly with different logo dimensions. Do you want these changes to be merged as well?

**Comment by gjb2048** [comment]
Hi Don,

At the moment I have no business case to make a M3.0 version and it would take a few days as there are LESS changes between M2.9 and 3.0.

If your client could sponsor the theme then that would be great.

As there are over 8200 sites using Essential, if they all gave me 10p then I would have 820 GBP which would be more than enough to make the M3.0 version a reality.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Thanks Mikhail,

But not perhaps at the moment.  Functionality wise I want to leave things as much as possible as the support workload increases the more there is.

Please test the branch and see if I have not made any mistakes.

Kind regards,

Gareth

**Comment by dschwa** [comment]
Put up a gofundme and I along with many others would help.

**Comment by gjb2048** [comment]
I already have a flattr and that is not working.

**Comment by gjb2048** [comment]
And I'm not asking for donations, but sponsorship.

**Comment by mikhailjan** [comment]
I'm willing to help create a M3.0 version since the company I work at will need to upgrade to M3.0 early next year.

Gareth if you could create a list of things that need to be done I can start on it.

**Comment by gjb2048** [comment]
Thanks Mikhail,

I don't know that list of things until I start actually testing and working on it, and perform a full comparison of the changes between bootstrapbase in M2.9 and M3.0.

But I'll make a start on that when I get time, other priorities at the moment.

Cheers,

Gareth

**Comment by mikhailjan** [comment]
Okay cool, there's no rush from my side.

Cheers,
Mikhail

**Comment by gjb2048** [comment]
Another site I've used is http://www.moodlegarage.com/ - as run by MoodleNews.  However, the last campaign I ran for the Grid format only made half of the money requested for the task which turned out to be a third of the development cost.

**Comment by gjb2048** [comment]
Implemented in: https://github.com/gjb2048/moodle-theme_essential/tree/MOODLE_29_%23574

**Pull request closed without merging**
