### PR TITLE
Add icon replacements for t/message and t/addcontact

### PR DESCRIPTION
**Pull request by Dagefoerde**
Moodle 3.2 has a new message center. We need a FontAwesome replacement for `t/message` in order to make it look nicer as well as more consistent. I suggest `fa-envelope-o`.

Before:
before

After:
after

This has an effect on `user/profile.php` since `t/message` is used there, too. I think that using a FontAwesome replacement there improves this page as well. However, for consistency we have to replace `t/addcontact`; I suggest `fa-address-card-o`.

Before:
before-profile

After:
after-profile

What do you think? :)
Best wishes

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks Jan, I'll consider the patch.

**Comment by gjb2048** [comment]
Hi Jan,

Ok, I disagree with the envelope as that implies eMail and given the conversation on: https://tracker.moodle.org/browse/MDL-57419 would be misleading.  Therefore perhaps 'fa-comment-o'?

G

**Comment by Dagefoerde** [comment]
Hi Gareth, 
Thanks for your consideration. I chose the envelope because that is the icon you used in the navigation bar. I merely did not want to introduce another icon for the same thing. 
I do get your point, though. What do you think of fa-comment*s*-o? That is the icon you use *within* the messaging menu for each conversation. We could reuse that.

**Comment by gjb2048** [comment]
fa-comments-o sounds good and better than my suggestion.

**Comment by Dagefoerde** [comment]
Thanks, I updated the branch accordingly. 

Profile:
profile-next

Messages:
messages-next

Best wishes and good night
Jan

**Pull request merged**
