### PR TITLE
Fixes #736 add extra urlcolor for stripes.

### LINKED ISSUE #736: Stripes on grade-report even rows use incorrect color for links
on the grader report on even rows the text colour of links (names, magnifying glass etc) uses the textcolor instead of the correct link colours.

looks like it's related to the color: inherit line here:
https://github.com/gjb2048/moodle-theme_essential/blame/master/style/essential-settings.css#L1059

removing the line color: inherit makes the links use the correct color.

hopefully that makes sense - let me know if you need a screnshot and I'll send one through.

### PR DESCRIPTION
**Pull request by danmarsden**
didn't compile the css files as I figured you might want to do those separately - also not sure about the default colour values - let me know if you want me to make any other changes! - thanks!

### CODE REVIEW

**Comment by gjb2048** [comment]
Thanks for the patch Dan,

A few points that need fixing please:

- I'll leave it up to you to choose a suitable colour for the alternative link that compliments the background 'ff9a34'.
- Alternative LESS is incorrect here: https://github.com/gjb2048/moodle-theme_essential/pull/738/commits/4f80b5890f6b3723e937bdccc98345d3b6f2aa07#diff-5180ee7b5a17662ef109190600d7a1a5R1129 as you are using this setting: https://github.com/gjb2048/moodle-theme_essential/pull/738/commits/4f80b5890f6b3723e937bdccc98345d3b6f2aa07#diff-3a8270dae2b17999b935edc868c22cebR365 and not this setting: https://github.com/gjb2048/moodle-theme_essential/pull/738/commits/4f80b5890f6b3723e937bdccc98345d3b6f2aa07#diff-3a8270dae2b17999b935edc868c22cebR633 because of the naming and lack of LESS iterator index as can be seen in the surrounding sheet: https://github.com/gjb2048/moodle-theme_essential/pull/738/commits/4f80b5890f6b3723e937bdccc98345d3b6f2aa07#diff-5180ee7b5a17662ef109190600d7a1a5R1126

Please rectify and resubmit as a single commit, thanks,

Gareth

**Comment by gjb2048** [comment]
P.S. Also the patch does not solve the original problem as now there is a stripe url colour for the odd rows the even rows don't use the theme url colour setting (and likewise for the alternative version too).

**Comment by danmarsden** [comment]
whoops - forgot to check/test the alternative less changes - will fix that up. I assumed the link for the other rows still came from the theme url colour setting - will take another look at that too. Thanks.

**Comment by danmarsden** [comment]
in my testing (chrome) the even rows seem to get the standard themeurlcolor colour and the odd rows get the new setting with the current patch.. although only in the grader report which is probably wrong and it needs to be applied to other stripe types as well. I'm not clear what you were saying in comment: https://github.com/gjb2048/moodle-theme_essential/pull/738#issuecomment-244314375

**Comment by danmarsden** [comment]
I've updated the branch with the changes - including applying the stripe url colour to normal stripes as well as the grader report. Let me know if this makes sense? - thanks!

**Comment by gjb2048** [comment]
Thanks Dan,

I'll review when I get a chance.

G

**Comment by gjb2048** [comment]
Not forgotten, just busy.

**Comment by danmarsden** [comment]
haha - no need for the update! - I know the feeling... I have had community stuff sit in my queue for a while myself!

**Comment by gjb2048** [comment]
Making this an enhancement in M3.1 as I think that's where I've done other stuff to tables.  Humm, may change my mind at a later date.

**Comment by gjb2048** [comment]
Ok, 'themestripetextcolour' is an M3.1 thing.

**Comment by gjb2048** [comment]
Oh poop, did a search on 'themestripetextcolour' and there are other places where there are urls and the new setting has been applied, drat drat and double drat.

**Comment by gjb2048** [comment]
Stripe url defaults are wrong, using: http://paletton.com/#uid=20-0u0kpuw0f-JNkQBnv3t8v+ms etc.

**Comment by danmarsden** [comment]
crap - sorry, sometimes it's just easier to write the code yourself rather than reviewing community contributed pull requests! - especially when you know the code much better than anyone else! - thanks for taking a look anyway!

**Comment by gjb2048** [comment]
No worries Dan, thanks for the patch and your time :)

**Pull request merged**
