### PR TITLE
4th alternative color scheme for the essential theme.

### PR DESCRIPTION
**Pull request by relecand**
Some institutions would like to have more than 3 alternative color schemes. This is the 4th.

### CODE REVIEW

**Comment by relecand** [comment]
screenshot 2015-09-10 11 30 11

**Comment by gjb2048** [comment]
Thanks for the patch.

However, this would mean even more maintenance work for me with yet another file to maintain 'alternative4.less' which as a typo in the first line comment.

You say 'some institutions' but do not name them.  Therefore I will consider this as a 'child theme' enhancement in future and not put in the main release.

**Comment by relecand** [comment]
I corrected the typo in 'alternative4.less'. 'alternative4.less' is very similar to 'alternative3.less' :)

**Comment by gjb2048** [comment]
Defaults for the forth are the same as the third: https://github.com/gjb2048/moodle-theme_essential/pull/532/files#diff-3a8270dae2b17999b935edc868c22cebR275.

Editor metadata removed in https://github.com/sudile/moodle-theme_essential/commit/43bdd613e39a31f49ca27f406092cf2993d1fca5 has crept back in here: https://github.com/gjb2048/moodle-theme_essential/pull/532/files#diff-a084b794bc0759e7a6b77810e01874f2R15

Plus I still need an answer to "You say 'some institutions' but do not name them" - before I put in time and effort reviewing and maintaining an enhancement, I need a good reason.  If I do this, then what's to stop somebody wanting a fifth?  Who 'definitely' needs four additional schemes?

This patch is also on the M2.8 branch, the M2.9 (master) branch is where all development goes, then back-ported.  Plus before this happens, then this: https://github.com/gjb2048/moodle-theme_essential/issues/520 needs fixing first to avoid even more duplication work.

**Comment by relecand** [comment]
Ok - I removed metadata and set new default colors for the 4th color scheme

Who needs this? We are supporting German universities in Moodle - in the next six month we will introduce the essential theme to three universities. All of them want to have different colors for their faculties (two of them have 5 faculties).

**Comment by gjb2048** [comment]
Thanks for the information, I will use it in my decision making process.

**Comment by gjb2048** [comment]
Is this a part of a paid contract?

**Comment by relecand** [comment]
Hi again,

would be great if you could provide the 4th alternative color scheme. If it helps: what would it cost to integrate it? Please answer via emai: christian dot niemczik at googlemail dot com

**Comment by gjb2048** [comment]
Hi again Jon,

I will only consider when M2.9 is stable, as you've now observed changes with #543 and #544 that with a fourth style would have taken me longer.

Thank you for the offer of paying for the enhancement, I will consider it.  But to be fair can only be worked out once M2.9 is stable.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
In any event, the pull patch code is now out of date.

**Comment by gjb2048** [comment]
Ok, I will do this for a fee, I'll message Christian.  Given #547 and #548 will definitely do after all bugs ironed out.

**Comment by relecand** [comment]
Ok, great.

**Comment by gjb2048** [comment]
Ok, this will happen.

It will be faster for me to implement and test rather than review and test, spotted another issue here: https://github.com/gjb2048/moodle-theme_essential/pull/532/files#diff-828043dc9f8d10ccd58ff8b96297794fR340

Will use defaults specified here: https://github.com/gjb2048/moodle-theme_essential/pull/532/files#diff-3a8270dae2b17999b935edc868c22cebR274

being:

    $defaultalternativethemecolors = array('#a430d1', '#d15430', '#5dd130','#006b94');
    $defaultalternativethemehovercolors = array('#9929c4', '#c44c29', '#53c429','#4090AF');

**Comment by gjb2048** [comment]
Implemented in https://github.com/gjb2048/moodle-theme_essential/commit/3d8f8a5217e403e841c7d42de7c016948050c591

**Pull request closed without merging**
