### PR TITLE
Increase performance of icon rendering functions

### PR DESCRIPTION
**Pull request by Dagefoerde**
This pull request contains my ideas for solving issue #634. Motivation and details are described there. In essence, this pull request proposes

* Better handling of the icon replacements array, thus saving memory operations (and, possibly, memory).
* Reduce the number of calls to `replace_moodle_icon` from two to one call for each icon.

### CODE REVIEW

**Comment by gjb2048** [comment]
I will add to the list of 'stuff' and get around to it at come point.  But MUST pass the TravisCI checks.

**Comment by gjb2048** [comment]
And, this is a MUST, as I will backport the fix, then there MUST be only ONE commit.  Therefore, rejected already.

**Comment by Dagefoerde** [comment]
I will keep the branch with multiple commits alive, if only for explanatory purposes :) As soon as Travis checks pass, I will create another pull request containing only a single pull request and close this one.

**Comment by Dagefoerde** [comment]
Superseded by #637.

**Pull request closed without merging**
